spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 18934665193pl,
      driver-class-name: com.mysql.cj.jdbc.Driver
      validation-query: SELECT 1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名 Table{create_time} <-> Entity{createTime}
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）